// main_window.h
#ifndef MAIN_WINDOW_H
#define MAIN_WINDOW_H

#include <QWidget>
#include "ui_main_window.h"
#include "database_handler.h"
#include "splay_tree.h"

class MainWindow : public QWidget {
    Q_OBJECT

public:
    explicit MainWindow(QWidget *parent = nullptr);
    ~MainWindow();

private slots:
    void onSearch();
    void onInsert();
    void onDelete();
    void onDisplayCache();
    void onExit();

private:
    Ui::MainWindow ui;  // UI class generated by Qt Designer
    DatabaseHandler dbHandler;  // Database handler object
    SplayTree cache;            // Cache (Splay Tree) object
    void logTimeElapsed(const std::string &operation, const std::chrono::high_resolution_clock::time_point &start, const std::chrono::high_resolution_clock::time_point &stop);
};

#endif // MAIN_WINDOW_H
